export const defaultImage =
  "https://images.unsplash.com/photo-1533105079780-92b9be482077?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80";
export const exampleData = [
  {
    id: 1,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: "web development",
    views: 100,
    publish: false,
  },
  {
    id: 2,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: "web development",
    views: 100,
    publish: true,
  },
  {
    id: 3,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: "web development",
    views: 100,
    publish: false,
  },
  {
    id: 4,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: "web development",
    views: 100,
    publish: false,
  },
  {
    id: 5,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: "web development",
    views: 100,
    publish: true,
  },
  {
    id: 6,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: "web development",
    views: 100,
    publish: true,
  },
  {
    id: 7,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: "web development",
    views: 100,
    publish: true,
  },
  {
    id: 8,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: "web development",
    views: 100,
    publish: true,
  },
  {
    id: 9,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: "web development",
    views: 100,
    publish: true,
  },
  {
    id: 10,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: "web development",
    views: 100,
    publish: true,
  },
];
