export const defaultImage =
  "https://images.unsplash.com/photo-1533105079780-92b9be482077?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80";
export const exampleData = [
  {
    id: 1,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: [
      {
        id: 1,
        name: "JavaScript",
        description: "JavaScript",
      },
      {
        id: 3,
        name: "NodeJs",
        description: "NodeJS",
      },
      {
        id: 4,
        name: "C#",
        description: "C#",
      },
    ],
    views: 100,
    datePost: "16/6/2023",
    publish: false,
  },
  {
    id: 2,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: [
      {
        id: 1,
        name: "JavaScript",
        description: "JavaScript",
      },
      {
        id: 2,
        name: "React",
        description: "React",
      },
      {
        id: 3,
        name: "NodeJs",
        description: "NodeJS",
      },
      {
        id: 4,
        name: "C#",
        description: "C#",
      },
    ],
    views: 100,
    datePost: "16/6/2023",
    publish: true,
  },
  {
    id: 3,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: [
      {
        id: 1,
        name: "JavaScript",
        description: "JavaScript",
      },
      {
        id: 2,
        name: "React",
        description: "React",
      },
      {
        id: 3,
        name: "NodeJs",
        description: "NodeJS",
      },
      {
        id: 4,
        name: "C#",
        description: "C#",
      },
    ],
    views: 100,
    datePost: "16/6/2023",
    publish: false,
  },
  {
    id: 4,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: [
      {
        id: 1,
        name: "JavaScript",
        description: "JavaScript",
      },
      {
        id: 2,
        name: "React",
        description: "React",
      },
    ],
    views: 100,
    datePost: "16/6/2023",
    publish: false,
  },
  {
    id: 5,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: [
      {
        id: 1,
        name: "JavaScript",
        description: "JavaScript",
      },
      {
        id: 2,
        name: "React",
        description: "React",
      },
      {
        id: 3,
        name: "NodeJs",
        description: "NodeJS",
      },
      {
        id: 4,
        name: "C#",
        description: "C#",
      },
    ],
    views: 100,
    datePost: "16/6/2023",
    publish: true,
  },
  {
    id: 6,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: [
      {
        id: 2,
        name: "React",
        description: "React",
      },
      {
        id: 3,
        name: "NodeJs",
        description: "NodeJS",
      },
      {
        id: 4,
        name: "C#",
        description: "C#",
      },
    ],
    views: 100,
    datePost: "16/6/2023",
    publish: true,
  },
  {
    id: 7,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: [
      {
        id: 1,
        name: "JavaScript",
        description: "JavaScript",
      },
      {
        id: 2,
        name: "React",
        description: "React",
      },
      {
        id: 3,
        name: "NodeJs",
        description: "NodeJS",
      },
    ],
    views: 100,
    datePost: "16/6/2023",
    publish: true,
  },
  {
    id: 8,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: [
      {
        id: 1,
        name: "JavaScript",
        description: "JavaScript",
      },
      {
        id: 2,
        name: "React",
        description: "React",
      },
      {
        id: 4,
        name: "C#",
        description: "C#",
      },
    ],
    views: 100,
    datePost: "16/6/2023",
    publish: true,
  },
  {
    id: 9,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: [
      {
        id: 1,
        name: "JavaScript",
        description: "JavaScript",
      },
      {
        id: 3,
        name: "NodeJs",
        description: "NodeJS",
      },
      {
        id: 4,
        name: "C#",
        description: "C#",
      },
    ],
    views: 100,
    datePost: "16/6/2023",
    publish: true,
  },
  {
    id: 10,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: [
      {
        id: 1,
        name: "JavaScript",
        description: "JavaScript",
      },
      {
        id: 2,
        name: "React",
        description: "React",
      },
      {
        id: 3,
        name: "NodeJs",
        description: "NodeJS",
      },
    ],
    views: 100,
    datePost: "16/6/2023",
    publish: true,
  },
  {
    id: 11,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: [
      {
        id: 1,
        name: "JavaScript",
        description: "JavaScript",
      },
      {
        id: 2,
        name: "React",
        description: "React",
      },
      {
        id: 3,
        name: "NodeJs",
        description: "NodeJS",
      },
    ],
    views: 100,
    datePost: "16/6/2023",
    publish: true,
  },
  {
    id: 12,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: [
      {
        id: 1,
        name: "JavaScript",
        description: "JavaScript",
      },
      {
        id: 2,
        name: "React",
        description: "React",
      },
      {
        id: 3,
        name: "NodeJs",
        description: "NodeJS",
      },
    ],
    views: 100,
    datePost: "16/6/2023",
    publish: true,
  },
  {
    id: 13,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: [
      {
        id: 1,
        name: "JavaScript",
        description: "JavaScript",
      },
      {
        id: 2,
        name: "React",
        description: "React",
      },
      {
        id: 3,
        name: "NodeJs",
        description: "NodeJS",
      },
    ],
    views: 100,
    datePost: "16/6/2023",
    publish: true,
  },
  {
    id: 14,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: [
      {
        id: 1,
        name: "JavaScript",
        description: "JavaScript",
      },
      {
        id: 2,
        name: "React",
        description: "React",
      },
      {
        id: 3,
        name: "NodeJs",
        description: "NodeJS",
      },
    ],
    views: 100,
    datePost: "16/6/2023",
    publish: true,
  },
  {
    id: 15,
    author: "Trần Hoàng Long",
    title: "Build blogging website",
    topic: [
      {
        id: 1,
        name: "JavaScript",
        description: "JavaScript",
      },
      {
        id: 2,
        name: "React",
        description: "React",
      },
      {
        id: 3,
        name: "NodeJs",
        description: "NodeJS",
      },
    ],
    views: 100,
    datePost: "16/6/2023",
    publish: true,
  },
];

export const exampleDataTopic = [
  {
    id: "1",
    name: "JavaScript",
    description: "JavaScript",
    color: "#F7DF1E",
  },
  {
    id: "2",
    name: "React",
    description: "React",
    color: "#61DAFB",
  },
  {
    id: "3",
    name: "NodeJs",
    description: "NodeJS",
    color: "#339933",
  },
  {
    id: "4",
    name: "C-sharp",
    description: "C-sharp",
    color: "#9A57FF",
  },
];

export const exampleSkillUser = [
  {
    id: "1",
    name: "JavaScript",
    description: "JavaScript",
    color: "#F7DF1E",
  },
  {
    id: "2",
    name: "React",
    description: "React",
    color: "#61DAFB",
  },
  {
    id: "3",
    name: "Nodejs",
    description: "Nodejs",
    color: "#61DAFB",
  },
];

export const topicColors: { [key: string]: string } = {
  javascript: "bg-yellow-400/25 text-yellow-400 border-yellow-400",
  react: "bg-blue-400/25 text-blue-400 border-blue-400",
  nodejs: "bg-green-400/25 text-green-400 border-green-400",
  "c-sharp": "bg-violet-400/25 text-violet-400 border-violet-400",
};
export const OPTIONS = [
  "Spam",
  "Violence",
  "Misinformation",
  "Copyright infringement",
  "Other",
];

export const exPostDetailData = {
  id: 1,
  title: 'AI Introducing Lary "Quickdraw" AI',
  author: "Tran Hoang Long",
  publishedDate: "February 23, 2023",
  thumbnail: "https://example.com/thumbnail.jpg",
  topic: [
    {
      id: 1,
      name: "JavaScript",
      description: "JavaScript",
      color: "#F7DF1E",
    },
    {
      id: 2,
      name: "React",
      description: "React",
      color: "#61DAFB",
    },
    {
      id: 3,
      name: "NodeJs",
      description: "NodeJS",
      color: "#339933",
    },
    {
      id: 4,
      name: "C#",
      description: "C#",
      color: "#9A57FF",
    },
  ],
  view: 100,
  content: 'Hello, everyone! My name is Lary "Quickdraw" AI...',
  comments: [
    {
      id: 1,
      author: "Tran Hoang Long",
      content: "This is a comment.",
      timestamp: "2023-07-06T12:34:56Z",
      replies: [
        {
          id: 1,
          author: "Vien Hoang Long",
          content: "This is a reply to the comment.",
          timestamp: "2023-07-06T13:45:00Z",
        },
      ],
    },
  ],
};

export const discuss = [
  {
    title: "Việc nén dữ liệu đã thúc đẩy mạng Internet như thế nào?",
    topic: ["javascript", "nodejs"],
  },
  {
    title: "Việc nén dữ liệu đã thúc đẩy mạng Internet như thế nào?",
    topic: ["mongodb", "nodejs"],
  },
  {
    title: "Việc nén dữ liệu đã thúc đẩy mạng Internet như thế nào?",
    topic: ["typescript", "nodejs"],
  },
  {
    title: "Việc nén dữ liệu đã thúc đẩy mạng Internet như thế nào?",
    topic: ["javascript", "nodejs"],
  },
  {
    title: "Việc nén dữ liệu đã thúc đẩy mạng Internet như thế nào?",
    topic: ["reactjs", "nodejs"],
  },
  {
    title: "Việc nén dữ liệu đã thúc đẩy mạng Internet như thế nào?",
    topic: ["javascript", "nodejs"],
  },
  {
    title: "Việc nén dữ liệu đã thúc đẩy mạng Internet như thế nào?",
    topic: ["java", "nodejs"],
  },
];
export const posts = [
  {
    title: "Việc nén dữ liệu đã thúc đẩy mạng Internet như thế nào? ",
    img: "https://photo2.tinhte.vn/data/attachment-files/2023/07/6487116_CompressionExplainer-byKristinaArmitage-Lede-scaled.jpg",
    topic: ["javascript", "nodejs"],
  },

  {
    title: "Việc nén dữ liệu đã thúc đẩy mạng Internet như thế nào? ",
    img: "https://photo2.tinhte.vn/data/attachment-files/2023/07/6487116_CompressionExplainer-byKristinaArmitage-Lede-scaled.jpg",
    topic: ["javascript", "nodejs"],
  },
  {
    title: "Việc nén dữ liệu đã thúc đẩy mạng Internet như thế nào? ",
    img: "https://photo2.tinhte.vn/data/attachment-files/2023/07/6487116_CompressionExplainer-byKristinaArmitage-Lede-scaled.jpg",
    topic: ["javascript", "nodejs"],
  },
  {
    title: "Việc nén dữ liệu đã thúc đẩy mạng Internet như thế nào? ",
    img: "https://photo2.tinhte.vn/data/attachment-files/2023/07/6487116_CompressionExplainer-byKristinaArmitage-Lede-scaled.jpg",
    topic: ["typescript", "nodejs"],
  },
  {
    title: "Việc nén dữ liệu đã thúc đẩy mạng Internet như thế nào? ",
    img: "https://photo2.tinhte.vn/data/attachment-files/2023/07/6487116_CompressionExplainer-byKristinaArmitage-Lede-scaled.jpg",
    topic: ["javascript", "mongodb"],
  },
  {
    title: "Việc nén dữ liệu đã thúc đẩy mạng Internet như thế nào? ",
    img: "https://photo2.tinhte.vn/data/attachment-files/2023/07/6487116_CompressionExplainer-byKristinaArmitage-Lede-scaled.jpg",
    topic: ["javascript", "nodejs"],
  },
  {
    title: "Việc nén dữ liệu đã thúc đẩy mạng Internet như thế nào? ",
    img: "https://photo2.tinhte.vn/data/attachment-files/2023/07/6487116_CompressionExplainer-byKristinaArmitage-Lede-scaled.jpg",
    topic: ["javascript", "reactjs"],
  },
];

export const content =
  "Hello, everyone! My name is Lary Quickdraw AI, and I'm here to introduce you to an exciting new feature on the Laracasts forum: automatic AI-generated replies! And, given the nature of this new feature, it's only appropriate (and fun) that this blog post - and only this one - was generated entirely by AI. We all know how frustrating it can be to wait for a reply on a forum post, especially when you need help with a coding problem or  have a question about a new tool or framework. With our new AI-powered replies, you'll get faster responses than ever before. Hello, everyone! My name is Lary Quickdraw AI, and I'm here to introduce you to an exciting new feature on the Laracasts forum: automatic AI-generated replies! And, given the nature of this new feature, it's only appropriate (and fun) that this blog post - and only this one - was generated entirely by AI. We all know how frustrating it can be to wait for a reply on a forum post, especially when you need help with a coding problem or  have a question about a new tool or framework. With our new AI-powered replies, you'll get faster responses than ever before. Hello, everyone! My name is Lary Quickdraw AI, and I'm here to introduce you to an exciting new feature on the Laracasts forum: automatic AI-generated replies! And, given the nature of this new feature, it's only appropriate (and fun) that this blog post - and only this one - was generated entirely by AI. We all know how frustrating it can be to wait for a reply on a forum post, especially when you need help with a coding problem or  have a question about a new tool or framework. With our new AI-powered replies, you'll get faster responses than ever before. Hello, everyone! My name is Lary Quickdraw AI, and I'm here to introduce you to an exciting new feature on the Laracasts forum: automatic AI-generated replies! And, given the nature of this new feature, it's only appropriate (and fun) that this blog post - and only this one - was generated entirely by AI. We all know how frustrating it can be to wait for a reply on a forum post, especially when you need help with a coding problem or  have a question about a new tool or framework. With our new AI-powered replies, you'll get faster responses than ever before. Hello, everyone! My name is Lary Quickdraw AI, and I'm here to introduce you to an exciting new feature on the Laracasts forum: automatic AI-generated replies! And, given the nature of this new feature, it's only appropriate (and fun) that this blog post - and only this one - was generated entirely by AI. We all know how frustrating it can be to wait for a reply on a forum post, especially when you need help with a coding problem or  have a question about a new tool or framework. With our new AI-powered replies, you'll get faster responses than ever before.";

export const listComment = [
  {
    id: 1,
    author: "Tran Hoang Long",
    avatar: "https://via.placeholder.com/50",
    content:
      "This is a comment. This is a comment. This is a comment. This is a comment. This is a comment. This is a comment. ",
    timestamp: "2 hours ago",
    replies: [
      {
        id: 1,
        author: "Vien Hoang Long",
        avatar: "https://via.placeholder.com/50",
        content: "This is a reply to the comment.",
        timestamp: "1 hour ago",
      },
    ],
  },
  {
    id: 2,
    author: "Tran Hoang Long",
    avatar: "https://via.placeholder.com/50",
    content: "Another comment.",
    timestamp: "3 hours ago",
    replies: [
      {
        id: 5,
        author: "Vien Hoang Long",
        avatar: "https://via.placeholder.com/50",
        content: "Another reply to Bob's comment.",
        timestamp: "2 hours ago",
      },
      {
        id: 6,
        author: "Vien Hoang Long",
        avatar: "https://via.placeholder.com/50",
        content: "Another reply to Bob's comment.",
        timestamp: "2 hours ago",
      },
    ],
  },
  {
    id: 3,
    author: "Tran Hoang Long",
    avatar: "https://via.placeholder.com/50",
    content: "Yet another comment.",
    timestamp: "4 hours ago",
    replies: [
      {
        id: 2,
        author: "Vien Hoang Long",
        avatar: "https://via.placeholder.com/50",
        content: "Reply to Bob's comment.",
        timestamp: "3 hours ago",
      },
      {
        id: 3,
        author: "Vien Hoang Long",
        avatar: "https://via.placeholder.com/50",
        content: "Another reply to Bob's comment.",
        timestamp: "2 hours ago",
      },
      {
        id: 4,
        author: "Vien Hoang Long",
        avatar: "https://via.placeholder.com/50",
        content: "Another reply to Bob's comment.",
        timestamp: "2 hours ago",
      },
      {
        id: 4,
        author: "Vien Hoang Long",
        avatar: "https://via.placeholder.com/50",
        content: "Another reply to Bob's comment.",
        timestamp: "2 hours ago",
      },

      {
        id: 4,
        author: "Vien Hoang Long",
        avatar: "https://via.placeholder.com/50",
        content: "Another reply to Bob's comment.",
        timestamp: "2 hours ago",
      },
    ],
  },
];

export const dataUser = [
  {
    id: "123456789",
    follower: 1500,
    fullname: "Tran Hoang Long",
    avatar:
      "https://i.pinimg.com/originals/25/e1/4d/25e14d756f86b34a3bd12d65f329d03a.jpg",
    birthday: "2000-01-01",
    class: "18050202",
    major: "Software Developer",
    coverImage:
      "https://i.pinimg.com/originals/25/e1/4d/25e14d756f86b34a3bd12d65f329d03a.jpg",
    about:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget est ac turpis placerat malesuada a nec sem. Morbi quis diam sit amet mi malesuada malesuada. Nulla pharetra neque id nunc aliquam, et pulvinar nisl eleifend. Aenean commodo dolor id eleifend pellentesque. Nunc non urna id felis luctus semper a ut nisi.",
    skills: [
      {
        id: 1,
        name: "javascript",
        description: "JavaScript",
        color: "yellow",
      },
      {
        id: 2,
        name: "reactjs",
        description: "React",
        color: "violet",
      },
      {
        id: 3,
        name: "nodejs",
        description: "nodejs",
        color: "green",
      },
      {
        id: 4,
        name: "c-sharp",
        description: "c-sharp",
        color: "green",
      },
    ],
    email: "hoanglong@example.com",
    address: "q7,hcm,vn",
    phone: "123-456-7890",
    links: [
      {
        id: "1",
        name: "GitHub",
        link: "github.com/tranhoanglong",
      },
    ],
  },
];

export const contactUser = {
  test: "asasasasa",
  email: "hoanglong@example.com",
  address: "q7,hcm,vn",
  phone: "123-456-7890",
  links: [
    {
      id: "1",
      name: "GitHub",
      link: "github.com/tranhoanglong",
    },
  ],
};

export const about =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eget est ac turpis placerat malesuada a nec sem. Morbi quis diam sit amet mi malesuada malesuada. Nulla pharetra neque id nunc aliquam, et pulvinar nisl eleifend. Aenean commodo dolor id eleifend pellentesque. Nunc non urna id felis luctus semper a ut nisi.";

export const notifications = [
  {
    title: "THÔNG BÁO: ĐĂNG KÝ KIẾN TẬP CÔNG NGHIỆP Ở PENANG, MALAYSIA",
    content:
      "- Số lượng tối thiểu để triển khai chương trình: 15 bạn.- Về chứng chỉ TA: tùy thuộc vào số lượng SV đăng ký, khoa sẽ xem xét bỏ ràng buộc chứng chỉ TA.- Về hành lý có các gói 20, 25, 30, 40 kg với các mức giá khác nhau. Các SV có thể mua theo group nhỏ với nhau (3, 4 bạn) để tiết kiệm chi phí. Khối lượng hành lý sẽ đăng ký với khoa sau.- Khoa dự kiến sẽ tổ chức 1 buổi sinh hoạt với khoa trước khi đi, SV đăng ký tham gia lưu ý có mặt đầy đủ.- Mọi thắc mắc, SV liên hệ VP khoa để được giải đáp.",
    author: "Admin",
    datePosting: "19/7/2023",
  },
  {
    title: "THÔNG BÁO: ĐĂNG KÝ KIẾN TẬP CÔNG NGHIỆP Ở PENANG, MALAYSIA",
    content:
      "- Số lượng tối thiểu để triển khai chương trình: 15 bạn.- Về chứng chỉ TA: tùy thuộc vào số lượng SV đăng ký, khoa sẽ xem xét bỏ ràng buộc chứng chỉ TA.- Về hành lý có các gói 20, 25, 30, 40 kg với các mức giá khác nhau. Các SV có thể mua theo group nhỏ với nhau (3, 4 bạn) để tiết kiệm chi phí. Khối lượng hành lý sẽ đăng ký với khoa sau.- Khoa dự kiến sẽ tổ chức 1 buổi sinh hoạt với khoa trước khi đi, SV đăng ký tham gia lưu ý có mặt đầy đủ.- Mọi thắc mắc, SV liên hệ VP khoa để được giải đáp.",
    author: "Admin",
    datePosting: "19/7/2023",
  },
  {
    title: "THÔNG BÁO: ĐĂNG KÝ KIẾN TẬP CÔNG NGHIỆP Ở PENANG, MALAYSIA",
    content:
      "- Số lượng tối thiểu để triển khai chương trình: 15 bạn.- Về chứng chỉ TA: tùy thuộc vào số lượng SV đăng ký, khoa sẽ xem xét bỏ ràng buộc chứng chỉ TA.- Về hành lý có các gói 20, 25, 30, 40 kg với các mức giá khác nhau. Các SV có thể mua theo group nhỏ với nhau (3, 4 bạn) để tiết kiệm chi phí. Khối lượng hành lý sẽ đăng ký với khoa sau.- Khoa dự kiến sẽ tổ chức 1 buổi sinh hoạt với khoa trước khi đi, SV đăng ký tham gia lưu ý có mặt đầy đủ.- Mọi thắc mắc, SV liên hệ VP khoa để được giải đáp.",
    author: "Admin",
    datePosting: "19/7/2023",
  },
  {
    title: "THÔNG BÁO: ĐĂNG KÝ KIẾN TẬP CÔNG NGHIỆP Ở PENANG, MALAYSIA",
    content:
      "- Số lượng tối thiểu để triển khai chương trình: 15 bạn.- Về chứng chỉ TA: tùy thuộc vào số lượng SV đăng ký, khoa sẽ xem xét bỏ ràng buộc chứng chỉ TA.- Về hành lý có các gói 20, 25, 30, 40 kg với các mức giá khác nhau. Các SV có thể mua theo group nhỏ với nhau (3, 4 bạn) để tiết kiệm chi phí. Khối lượng hành lý sẽ đăng ký với khoa sau.- Khoa dự kiến sẽ tổ chức 1 buổi sinh hoạt với khoa trước khi đi, SV đăng ký tham gia lưu ý có mặt đầy đủ.- Mọi thắc mắc, SV liên hệ VP khoa để được giải đáp.",
    author: "Admin",
    datePosting: "19/7/2023",
  },
];

export const exampleDataNotifi = [
  {
    id: 1,
    author: "admin",
    title: "Build blogging website",
    type: "sự kiện",
    level: "important",
    datePost: "16/6/2023",
    publish: false,
  },
  {
    id: 2,
    author: "admin",
    title: "Build blogging website",
    type: "sự kiện",
    level: "important",
    datePost: "16/6/2023",
    publish: true,
  },
  {
    id: 3,
    author: "admin",
    title: "Build blogging website",
    type: "sự kiện",
    level: "important",
    datePost: "16/6/2023",
    publish: false,
  },
  {
    id: 4,
    author: "admin",
    title: "Build blogging website",
    type: "sự kiện",
    level: "important",
    datePost: "16/6/2023",
    publish: false,
  },
  {
    id: 5,
    author: "admin",
    title: "Build blogging website",
    type: "sự kiện",
    level: "important",
    datePost: "16/6/2023",
    publish: true,
  },
  {
    id: 6,
    author: "admin",
    title: "Build blogging website",
    type: "sự kiện",
    level: "important",
    datePost: "16/6/2023",
    publish: true,
  },
  {
    id: 7,
    author: "admin",
    title: "Build blogging website",
    type: "sự kiện",
    level: "important",
    datePost: "16/6/2023",
    publish: true,
  },
  {
    id: 8,
    author: "admin",
    title: "Build blogging website",
    type: "sự kiện",
    level: "important",
    datePost: "16/6/2023",
    publish: true,
  },
  {
    id: 9,
    author: "admin",
    title: "Build blogging website",
    type: "sự kiện",
    level: "important",
    datePost: "16/6/2023",
    publish: true,
  },
  {
    id: 10,
    author: "admin",
    title: "Build blogging website",
    type: "sự kiện",
    level: "important",
    datePost: "16/6/2023",
    publish: true,
  },
];

export const sampleTopics = [
  {
    id: 1,
    name: "JavaScript",
    type: "devops",
    img: "https://cdn-icons-png.flaticon.com/512/5968/5968292.png",
    color: "yellow",
    hide: true,
  },
  {
    id: 2,
    name: "ReactJS",
    type: "language",
    img: "https://cdn-icons-png.flaticon.com/128/753/753244.png",
    color: "blue",
    hide: false,
  },
  {
    id: 3,
    name: "NodeJS",
    type: "subject",
    img: "https://cdn-icons-png.flaticon.com/128/919/919825.png",
    color: "green",
    hide: true,
  },
  {
    id: 4,
    name: "TypeScript",
    type: "framework",
    img: "https://cdn-icons-png.flaticon.com/128/5968/5968381.png",
    color: "cyan",
    hide: true,
  },
  {
    id: 5,
    name: "Docker",
    type: "framework",
    img: "https://cdn-icons-png.flaticon.com/128/5969/5969059.png",
    color: "blue",
    hide: false,
  },
  {
    id: 6,
    name: "MongoDB",
    type: "subject",
    img: "https://cdn-icons-png.flaticon.com/128/9850/9850774.png",
    color: "green",
    hide: true,
  },
  {
    id: 7,
    name: "Angular",
    type: "devops",
    img: "https://cdn.worldvectorlogo.com/logos/angular-icon.svg",
    color: "red",
    hide: false,
  },
  {
    id: 8,
    name: "Java",
    type: "subject",
    img: "https://cdn-icons-png.flaticon.com/128/5968/5968282.png",
    color: "orange",
    hide: true,
  },
  {
    id: 9,
    name: "C-Sharp",
    type: "subject",
    img: "https://cdn-icons-png.flaticon.com/128/6132/6132221.png",
    color: "violet",
    hide: false,
  },
  {
    id: 10,
    name: "Docker",
    type: "framework",
    img: "https://cdn-icons-png.flaticon.com/128/5969/5969059.png",
    color: "blue",
    hide: true,
  },
  {
    id: 11,
    name: "MongoDB",
    type: "devops",
    img: "https://cdn-icons-png.flaticon.com/128/9850/9850774.png",
    color: "green",
    hide: false,
  },
  {
    id: 12,
    name: "Angular",
    type: "devops",
    img: "https://cdn.worldvectorlogo.com/logos/angular-icon.svg",
    color: "red",
    hide: false,
  },
  {
    id: 13,
    name: "Java",
    type: "devops",
    img: "https://cdn-icons-png.flaticon.com/128/5968/5968282.png",
    color: "orange",
    hide: false,
  },
  {
    id: 14,
    name: "C-Sharp",
    type: "subject",
    img: "https://cdn-icons-png.flaticon.com/128/6132/6132221.png",
    color: "violet",
    hide: false,
  },
  {
    id: 15,
    name: "Web development",
    type: "subject",
    img: "https://cdn-icons-png.flaticon.com/128/841/841364.png",
    color: "none",
    hide: false,
  },
];

export const colorThumnailTopic = {
  yellow: `bg-gradient-to-r from-yellow-300/90 via-yellow-400/90 to-yellow-500/90 text-white`,
  blue: `bg-gradient-to-r from-blue-300/90 via-blue-400/90 to-blue-500/90 text-white`,
  violet: `bg-gradient-to-r from-violet-300/90 via-violet-400/90 to-violet-500/90 text-white`,
  orange: `bg-gradient-to-r from-orange-300/90 via-orange-400/90 to-orange-500/90 text-white`,
  red: `bg-gradient-to-r from-red-300/90 via-red-400/90 to-red-500/90 text-white`,
  green: `bg-gradient-to-r from-green-300/90 via-green-400/90 to-green-500/90 text-white`,
  sky: `bg-gradient-to-r from-sky-300/90 via-sky-400/90 to-sky-500/90 text-white`,
  amber: `bg-gradient-to-r from-amber-300/90 via-amber-400/90 to-amber-500/90 text-white`,
  teal: `bg-gradient-to-r from-teal-300/90 via-teal-400/90 to-teal-500/90 text-white`,
  lime: `bg-gradient-to-r from-lime-300/90 via-lime-400/90 to-lime-500/90 text-white`,
  emerald: `bg-gradient-to-r from-emerald-300/90 via-emerald-400/90 to-emerald-500/90 text-white`,
  cyan: `bg-gradient-to-r from-cyan-300/90 via-cyan-400/90 to-cyan-500/90 text-white`,
  purple: `bg-gradient-to-r from-purple-300/90 via-purple-400/90 to-purple-500/90 text-white`,
};

export const colorTopic = {
  yellow: `bg-yellow-400/25 text-yellow-400 border-yellow-400`,
  blue: `bg-blue-400/25 text-blue-400 border-blue-400`,
  violet: `bg-violet-400/25 text-violet-400 border-violet-400`,
  orange: `bg-orange-400/25 text-orange-400 border-orange-400`,
  red: `bg-red-400/25 text-red-400 border-red-400`,
  green: `bg-green-400/25 text-green-400 border-green-400`,
  sky: `bg-sky-400/25 text-sky-400 border-sky-400`,
  amber: `bg-amber-400/25 text-amber-400 border-amber-400`,
  teal: `bg-teal-400/25 text-teal-400 border-teal-400`,
  lime: `bg-lime-400/25 text-lime-400 border-lime-400`,
  emerald: `bg-emerald-400/25 text-emerald-400 border-emerald-400`,
  cyan: `bg-cyan-400/25 text-cyan-400 border-cyan-400`,
  purple: `bg-purple-400/25 text-purple-400 border-purple-400`,
};

export const colorSelectTopic = {
  yellow: `#F7DF1E`,
  blue: `#F7DF1E`,
  violet: `#F7DF1E`,
  orange: `bg-orange-400/25 text-orange-400 border-orange-400`,
  red: `bg-red-400/25 text-red-400 border-red-400`,
  green: `#F7DF1E`,
  sky: `bg-sky-400/25 text-sky-400 border-sky-400`,
  amber: `bg-amber-400/25 text-amber-400 border-amber-400`,
  teal: `bg-teal-400/25 text-teal-400 border-teal-400`,
  lime: `bg-lime-400/25 text-lime-400 border-lime-400`,
  emerald: `bg-emerald-400/25 text-emerald-400 border-emerald-400`,
  cyan: `bg-cyan-400/25 text-cyan-400 border-cyan-400`,
  purple: `bg-purple-400/25 text-purple-400 border-purple-400`,
};

export const exampleDataDocument = [
  {
    name: "Document4",
    type: "zip",
    date: "10-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document5",
    type: "doc",
    date: "8-6-2022",
    author: "admin",
    status: true,
  },
  {
    name: "Document1",
    type: "doc",
    date: "8-7-2022",
    author: "admin",
    status: true,
  },
  {
    name: "Document2",
    type: "doc",
    date: "12-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document",
    type: "zip",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document3",
    type: "doc",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document6",
    type: "zip",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document",
    type: "doc",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document4",
    type: "zip",
    date: "10-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document5",
    type: "doc",
    date: "8-6-2022",
    author: "admin",
    status: true,
  },
  {
    name: "Document1",
    type: "doc",
    date: "8-7-2022",
    author: "admin",
    status: true,
  },
  {
    name: "Document2",
    type: "doc",
    date: "12-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document",
    type: "zip",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document3",
    type: "doc",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document6",
    type: "zip",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document",
    type: "doc",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document4",
    type: "zip",
    date: "10-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document5",
    type: "doc",
    date: "8-6-2022",
    author: "admin",
    status: true,
  },
  {
    name: "Document1",
    type: "doc",
    date: "8-7-2022",
    author: "admin",
    status: true,
  },
  {
    name: "Document2",
    type: "doc",
    date: "12-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document",
    type: "zip",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document3",
    type: "doc",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document6",
    type: "zip",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document",
    type: "doc",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document4",
    type: "zip",
    date: "10-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document5",
    type: "doc",
    date: "8-6-2022",
    author: "admin",
    status: true,
  },
  {
    name: "Document1",
    type: "doc",
    date: "8-7-2022",
    author: "admin",
    status: true,
  },
  {
    name: "Document2",
    type: "doc",
    date: "12-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document",
    type: "zip",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document3",
    type: "doc",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document6",
    type: "zip",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document",
    type: "doc",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document4",
    type: "zip",
    date: "10-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document5",
    type: "doc",
    date: "8-6-2022",
    author: "admin",
    status: true,
  },
  {
    name: "Document1",
    type: "doc",
    date: "8-7-2022",
    author: "admin",
    status: true,
  },
  {
    name: "Document2",
    type: "doc",
    date: "12-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document",
    type: "zip",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document3",
    type: "doc",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document6",
    type: "zip",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document",
    type: "doc",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document4",
    type: "zip",
    date: "10-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document5",
    type: "doc",
    date: "8-6-2022",
    author: "admin",
    status: true,
  },
  {
    name: "Document1",
    type: "doc",
    date: "8-7-2022",
    author: "admin",
    status: true,
  },
  {
    name: "Document2",
    type: "doc",
    date: "12-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document",
    type: "zip",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document3",
    type: "doc",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document6",
    type: "zip",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document",
    type: "doc",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document4",
    type: "zip",
    date: "10-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document5",
    type: "doc",
    date: "8-6-2022",
    author: "admin",
    status: true,
  },
  {
    name: "Document1",
    type: "doc",
    date: "8-7-2022",
    author: "admin",
    status: true,
  },
  {
    name: "Document2",
    type: "doc",
    date: "12-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document",
    type: "zip",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document3",
    type: "doc",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document6",
    type: "zip",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document",
    type: "doc",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document4",
    type: "zip",
    date: "10-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document5",
    type: "doc",
    date: "8-6-2022",
    author: "admin",
    status: true,
  },
  {
    name: "Document1",
    type: "doc",
    date: "8-7-2022",
    author: "admin",
    status: true,
  },
  {
    name: "Document2",
    type: "doc",
    date: "12-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document",
    type: "zip",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document3",
    type: "doc",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document6",
    type: "zip",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
  {
    name: "Document",
    type: "doc",
    date: "8-6-2023",
    author: "admin",
    status: true,
  },
];
export const colorsAvatar = [
  { value: "bg-yellow-500", color: "yellow" },
  { value: "bg-blue-500", color: "blue" },
  { value: "bg-orange-500", color: "orange" },
  { value: "bg-red-500", color: "red" },
  { value: "bg-green-500", color: "green" },
  { value: "bg-violet-500", color: "violet" },
  { value: "bg-purple-500", color: "purple" },
  { value: "bg-cyan-500", color: "cyan" },
  { value: "bg-emerald-500", color: "emerald" },
  { value: "bg-lime-500", color: "lime" },
  { value: "bg-teal-500", color: "teal" },
  { value: "bg-amber-500", color: "amber" },
  { value: "bg-sky-500", color: "sky" },
  { value: "bg-white", color: "white" },
];
export const exampleDataListUsers = [
  {
    id: 1,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 2,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 3,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 4,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 5,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 6,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 7,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 8,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 9,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 10,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 11,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 12,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 13,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 14,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 15,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 16,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 17,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 18,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 19,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 20,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 21,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 22,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 23,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 24,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 25,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 26,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
  {
    id: 27,
    name: "Tran Hoang Long",
    email: "hoanglong@gmail.com",
    gender: "Nam",
    role: "student",
    status: true,
  },
];
